import type { DailyReport, CompanyIntelligence, UserConviction } from './firebase';

export class ExportService {
  /**
   * Helper to format currency values
   */
  private static formatCurrency(val: number, currency: string): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }).format(val);
  }

  /**
   * Helper to format percentage values
   */
  private static formatPercent(val: number): string {
    const sign = val > 0 ? '+' : '';
    return `${sign}${val.toFixed(2)}%`;
  }

  /**
   * Triggers browser download for a text file
   */
  private static downloadTextFile(content: string, filename: string) {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Generates and downloads Markdown for a Daily/Weekly Report
   */
  public static exportDailyReportToMarkdown(
    report: DailyReport,
    aiCommentary: any,
    currency = 'INR'
  ) {
    let md = `# ${report.title}\n\n`;
    md += `**Published:** ${new Date(report.createdAt).toLocaleString()}\n`;
    md += `**Index ID:** ${report.id.toUpperCase()}\n\n`;
    md += `## Executive Summary\n\n${report.summary}\n\n`;

    if (aiCommentary) {
      md += `## Gemini AI Editorial Intelligence\n\n`;
      md += `### Executive Summary\n${aiCommentary.executiveSummary || 'N/A'}\n\n`;
      md += `### Portfolio Commentary\n${aiCommentary.portfolioCommentary || 'N/A'}\n\n`;
      md += `### Market Context\n${aiCommentary.marketContext || 'N/A'}\n\n`;
    }

    md += `## Market Snapshot\n\n`;
    md += `* **Global Trend:** ${report.sections.marketSnapshot.globalTrend.toUpperCase()}\n`;
    md += `* **US Equities:** ${report.sections.marketSnapshot.usMarket}\n`;
    md += `* **Indian Markets:** ${report.sections.marketSnapshot.indianMarket}\n`;
    md += `* **Cryptocurrency:** ${report.sections.marketSnapshot.cryptoMarket}\n\n`;

    md += `## Portfolio Summary\n\n`;
    md += `* **Valuation:** ${this.formatCurrency(report.sections.portfolioSummary.totalValue, currency)}\n`;
    md += `* **Returns Basis:** ${this.formatCurrency(report.sections.portfolioSummary.totalGainLoss, currency)}\n`;
    md += `* **Ledger Posture:** ${report.sections.portfolioSummary.performanceLabel}\n`;
    md += `* **Highlights:** ${report.sections.portfolioSummary.allocationHighlights}\n\n`;

    md += `## Monitored Watchlist Movers\n\n`;
    if (report.sections.watchlistMovers && report.sections.watchlistMovers.length > 0) {
      report.sections.watchlistMovers.forEach(mover => {
        md += `* **${mover.ticker}** (${mover.exchange}): ${this.formatCurrency(mover.price, mover.exchange === 'NSE' || mover.exchange === 'BSE' ? 'INR' : 'USD')} (${mover.direction.toUpperCase()} ${this.formatPercent(mover.changePercent)})\n`;
      });
    } else {
      md += `No active watchlist items monitored.\n`;
    }
    md += `\n`;

    md += `## Risk Assessment\n\n`;
    if (report.sections.riskFlags && report.sections.riskFlags.length > 0) {
      report.sections.riskFlags.forEach(flag => {
        md += `* **[${flag.level.toUpperCase()}] ${flag.message}**\n  *Suggestion:* ${flag.suggestion}\n`;
      });
    } else {
      md += `No warning flags active. Portfolio in secure state.\n`;
    }
    md += `\n`;

    md += `## Term of the Day\n\n`;
    md += `**${report.sections.learningItem.term}**\n\n`;
    md += `*Definition:* ${report.sections.learningItem.definition}\n\n`;
    md += `*Context:* ${report.sections.learningItem.context}\n\n`;

    md += `---\n*Report generated by BusinessOS Unified Intelligence platform. Metadata and quotes synced at generation timestamp.*`;

    const cleanTitle = report.title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
    this.downloadTextFile(md, `${cleanTitle}_report.md`);
  }

  /**
   * Renders a styled Financial Times print window for a Daily/Weekly Report
   */
  public static exportDailyReportToPDF(
    report: DailyReport,
    aiCommentary: any,
    currency = 'INR'
  ) {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Pop-up blocker prevented generating PDF. Please enable pop-ups for this site.');
      return;
    }

    const dateStr = new Date(report.createdAt).toLocaleString();
    const moversHtml = report.sections.watchlistMovers && report.sections.watchlistMovers.length > 0
      ? report.sections.watchlistMovers.map(m => `
        <div style="display:flex; justify-content:space-between; border-bottom:1px dashed #D2CAC3; padding: 4px 0; font-size:13px; font-family:monospace;">
          <span><strong>${m.ticker}</strong> (${m.exchange})</span>
          <span>
            ${this.formatCurrency(m.price, m.exchange === 'NSE' || m.exchange === 'BSE' ? 'INR' : 'USD')}
            <span style="color: ${m.direction === 'up' ? '#006622' : '#cc0000'}; font-weight:bold; margin-left:6px;">
              ${m.direction === 'up' ? '▲' : '▼'} ${this.formatPercent(m.changePercent)}
            </span>
          </span>
        </div>
      `).join('')
      : '<p style="font-style:italic; font-size:12px; color:#555;">No watchlist items monitored.</p>';

    const risksHtml = report.sections.riskFlags && report.sections.riskFlags.length > 0
      ? report.sections.riskFlags.map(f => `
        <div style="border-left: 3px solid ${f.level === 'danger' ? '#cc0000' : '#d97706'}; padding-left: 8px; margin-bottom: 12px; font-size:12px;">
          <strong style="color: ${f.level === 'danger' ? '#cc0000' : '#9a3412'}; display:block;">[${f.level.toUpperCase()}] ${f.message}</strong>
          <span style="color:#444;">Suggestion: ${f.suggestion}</span>
        </div>
      `).join('')
      : '<p style="font-size:12px; color:#006622;">✓ No alert flags active. Portfolio metrics secure.</p>';

    const aiHtml = aiCommentary
      ? `
        <div style="background-color:#FAF8F5; border:1.5px solid #222; padding: 16px 20px; margin-bottom: 24px; box-shadow: 2px 2px 0px rgba(0,0,0,0.05);">
          <h3 style="font-family:'Courier New', monospace; font-size:13px; color:#c2410c; margin: 0 0 10px 0; text-transform:uppercase; letter-spacing:1px; font-weight:bold;">
             ✦ Gemini AI Editorial Commentary
          </h3>
          <p style="font-family:'Georgia', serif; font-size:14px; line-height:1.6; text-indent: 1.5em; margin: 0 0 14px 0; text-align:justify;">
            ${aiCommentary.executiveSummary}
          </p>
          <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px; border-top:1px dashed #C2B6A9; padding-top:12px;">
            <div>
              <h4 style="font-family:'Courier New', monospace; font-size:11px; margin:0 0 6px 0; font-weight:bold;">PORTFOLIO DISPATCH</h4>
              <p style="font-size:12px; line-height:1.4; color:#333; margin:0;">${aiCommentary.portfolioCommentary}</p>
            </div>
            <div>
              <h4 style="font-family:'Courier New', monospace; font-size:11px; margin:0 0 6px 0; font-weight:bold;">MACRO ENVIRONMENT</h4>
              <p style="font-size:12px; line-height:1.4; color:#333; margin:0;">${aiCommentary.marketContext}</p>
            </div>
          </div>
        </div>
      `
      : '';

    printWindow.document.write(`
      <html>
        <head>
          <title>${report.title}</title>
          <style>
            @media print {
              body { background-color: #FFFFFF !important; }
              .no-print { display: none; }
            }
            body {
              background-color: #FCFAF6;
              color: #111111;
              font-family: 'Georgia', serif;
              padding: 40px;
              max-width: 800px;
              margin: 0 auto;
              border: 1px solid #E5DFD5;
              box-sizing: border-box;
            }
            h1, h2, h3, h4, h5 {
              font-family: 'Times New Roman', Georgia, serif;
              font-weight: normal;
              margin: 0;
            }
            .header {
              text-align: center;
              border-bottom: 2px double #111;
              padding-bottom: 12px;
              margin-bottom: 24px;
            }
            .title {
              font-size: 32px;
              font-weight: bold;
              letter-spacing: -0.5px;
              line-height: 1.15;
              margin: 6px 0;
            }
            .meta {
              font-family: 'Courier New', Courier, monospace;
              font-size: 11px;
              color: #555;
              display: flex;
              justify-content: center;
              gap: 16px;
              text-transform: uppercase;
            }
            .summary {
              font-size: 15px;
              line-height: 1.6;
              font-style: italic;
              color: #222;
              border-bottom: 1px solid #E5DFD5;
              padding-bottom: 16px;
              margin-bottom: 24px;
              text-indent: 20px;
              text-align: justify;
            }
            .grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 32px;
            }
            .section-title {
              font-size: 14px;
              font-family: 'Courier New', monospace;
              font-weight: bold;
              text-transform: uppercase;
              border-bottom: 1.5px solid #111;
              padding-bottom: 4px;
              margin-bottom: 12px;
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            .metric-row {
              display: flex;
              justify-content: space-between;
              font-size: 13px;
              margin-bottom: 6px;
            }
          </style>
        </head>
        <body>
          <div class="no-print" style="margin-bottom: 20px; display: flex; justify-content: flex-end; gap: 8px;">
            <button onclick="window.print()" style="font-family:sans-serif; cursor:pointer; background:#222; color:#fff; border:none; padding:8px 16px; font-weight:bold; font-size:12px;">
              Print / Save as PDF
            </button>
            <button onclick="window.close()" style="font-family:sans-serif; cursor:pointer; background:#eee; color:#333; border:1px solid #ccc; padding:8px 16px; font-size:12px;">
              Close
            </button>
          </div>

          <div class="header">
            <span style="font-family:'Courier New', monospace; font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#555;">
              BusinessOS Editorial Board • Intelligence Division
            </span>
            <div class="title">${report.title}</div>
            <div class="meta">
              <span>Published: ${dateStr}</span>
              <span>•</span>
              <span>INDEX ID: ${report.id.toUpperCase()}</span>
            </div>
          </div>

          <div class="summary">
            ${report.summary}
          </div>

          ${aiHtml}

          <div class="grid">
            <div>
              <div style="margin-bottom: 24px;">
                <div class="section-title">
                  <span>Market Indices</span>
                  <span style="font-size:10px; background:#eee; padding: 1px 4px;">
                    ${report.sections.marketSnapshot.globalTrend.toUpperCase()}
                  </span>
                </div>
                <div style="font-size:13px; line-height:1.5; display:flex; flex-direction:column; gap:8px;">
                  <div>
                    <strong>US Equities:</strong>
                    <span style="color:#333;">${report.sections.marketSnapshot.usMarket}</span>
                  </div>
                  <div>
                    <strong>Indian Markets:</strong>
                    <span style="color:#333;">${report.sections.marketSnapshot.indianMarket}</span>
                  </div>
                  <div>
                    <strong>Cryptocurrency:</strong>
                    <span style="color:#333;">${report.sections.marketSnapshot.cryptoMarket}</span>
                  </div>
                </div>
              </div>

              <div>
                <div class="section-title">Portfolio Summary</div>
                <div class="metric-row">
                  <span>Valuation:</span>
                  <span style="font-family:monospace; font-weight:bold;">
                    ${this.formatCurrency(report.sections.portfolioSummary.totalValue, currency)}
                  </span>
                </div>
                <div class="metric-row">
                  <span>Returns Basis:</span>
                  <span style="font-family:monospace; font-weight:bold; color: ${report.sections.portfolioSummary.totalGainLoss >= 0 ? '#006622' : '#cc0000'};">
                    ${this.formatCurrency(report.sections.portfolioSummary.totalGainLoss, currency)}
                  </span>
                </div>
                <div class="metric-row">
                  <span>Ledger Posture:</span>
                  <span style="font-family:'Courier New', monospace; font-size:11px; font-weight:bold; background:#e5dfd5; padding:0 3px;">
                    ${report.sections.portfolioSummary.performanceLabel}
                  </span>
                </div>
                <p style="font-size:12px; color:#444; line-height:1.4; border-top:1px dashed #E5DFD5; padding-top:6px; margin-top:8px; font-style:italic;">
                  ${report.sections.portfolioSummary.allocationHighlights}
                </p>
              </div>
            </div>

            <div>
              <div style="margin-bottom: 24px;">
                <div class="section-title">Monitored Movers</div>
                ${moversHtml}
              </div>

              <div style="margin-bottom: 24px;">
                <div class="section-title">Risk Assessment</div>
                ${risksHtml}
              </div>

              <div style="background:#FAF8F5; border:1px solid #E5DFD5; padding:12px; font-size:12px; line-height:1.45;">
                <h5 style="font-family:'Courier New', monospace; color:#c2410c; margin:0 0 4px 0; text-transform:uppercase; font-weight:bold;">
                  Term of the Day
                </h5>
                <strong style="font-size:13px; display:block; margin-bottom:2px;">
                  ${report.sections.learningItem.term}
                </strong>
                <p style="margin:0 0 6px 0; color:#333;">${report.sections.learningItem.definition}</p>
                <p style="margin:0; font-style:italic; font-size:11px; color:#555; border-top:1px dashed #e2dacd; padding-top:4px;">
                  ${report.sections.learningItem.context}
                </p>
              </div>
            </div>
          </div>

          <div style="margin-top: 36px; border-top: 1px solid #111; padding-top: 8px; font-family:'Courier New', monospace; font-size:9px; text-align:center; color:#555; text-transform:uppercase;">
            Dispatch generated deterministically. Financial Times styling template applied.
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  /**
   * Generates and downloads Markdown for a Company Intelligence Report
   */
  public static exportIntelligenceReportToMarkdown(
    intel: CompanyIntelligence,
    conviction: UserConviction | null
  ) {
    let md = `# Company Intelligence Report: ${intel.name} (${intel.ticker}:${intel.exchange})\n\n`;
    md += `**Sector:** ${intel.sector}\n`;
    md += `**Quality Score:** ${intel.qualityScore}/100\n`;
    md += `**Generated:** ${new Date(intel.research.updatedAt).toLocaleString()}\n\n`;

    md += `## Economic Moat Rating\n\n`;
    md += `* **Moat Rating:** ${intel.research.moatRating.toUpperCase()}\n`;
    md += `* **Rationale:** ${intel.research.moatRationale}\n\n`;

    md += `## Quality Score Breakdown\n\n`;
    md += `* **Moat Rating Score:** ${intel.qualityBreakdown?.moat.score || 0} / 40\n`;
    md += `* **Leverage Score:** ${intel.qualityBreakdown?.leverage.score || 0} / 30 (Leverage Ratio: ${intel.research.leverageRatio.toFixed(2)})\n`;
    md += `* **FCF Margin Score:** ${intel.qualityBreakdown?.fcfMargin.score || 0} / 30 (FCF Margin: ${intel.research.freeCashFlowMargin.toFixed(1)}%)\n\n`;

    if (conviction) {
      md += `## Personal User Conviction Analysis\n\n`;
      md += `* **Overall Conviction Score:** ${conviction.overallScore}/100\n\n`;
      md += `### Score Contributors:\n`;
      md += `* **Allocation Factor:** ${conviction.breakdown.allocationFactor.contribution} / 25\n  *Explanation:* ${conviction.breakdown.allocationFactor.explanation}\n`;
      md += `* **Fundamental Quality:** ${conviction.breakdown.fundamentalFactor.contribution} / 25\n  *Explanation:* ${conviction.breakdown.fundamentalFactor.explanation}\n`;
      md += `* **Buy-The-Dip Premium:** ${conviction.breakdown.dipFactor.contribution} / 25\n  *Explanation:* ${conviction.breakdown.dipFactor.explanation}\n`;
      md += `* **Smart Money Flow:** ${conviction.breakdown.institutionalFactor.contribution} / 25\n  *Explanation:* ${conviction.breakdown.institutionalFactor.explanation}\n\n`;
    }

    md += `## Technical Dip Diagnostics\n\n`;
    md += `* **Dip Detected:** ${intel.dip.dipDetected ? 'YES' : 'NO'}\n`;
    if (intel.dip.dipDetected) {
      md += `* **Classification:** ${intel.dip.classification?.toUpperCase() || 'UNSTABLE'}\n`;
      md += `* **Deviation (Z-Score):** ${intel.dip.zScore?.toFixed(2)} sigma\n`;
      md += `* **Catalyst Narrative:** ${intel.dip.catalyst}\n`;
      md += `* **Heuristic Classification Rationale:** ${intel.dip.classificationRationale}\n\n`;
    } else {
      md += `Asset is within standard volatility ranges. No unusual price deviations flagged.\n\n`;
    }

    md += `## Institutional & Smart Money Flows\n\n`;
    md += `* **Insider Transactions:** ${intel.smartMoney.insiderTransactions?.value ? `${intel.smartMoney.insiderTransactions.value.netSharesBought.toLocaleString()} net shares bought in last 90 days (${intel.smartMoney.insiderTransactions.value.totalTransactionsCount} filings)` : 'Data unavailable'}\n`;
    md += `* **Corporate Officer Sentiment:** ${intel.smartMoney.insiderSentiment?.value ? `Monthly Purchase Ratio (MSPR) of ${intel.smartMoney.insiderSentiment.value.mspr.toFixed(2)}` : 'Data unavailable'}\n`;
    md += `* **Options Volume Flow:** ${intel.smartMoney.optionsVolume?.value ? `Put/Call Ratio: ${intel.smartMoney.optionsVolume.value.putCallRatio.toFixed(2)} (${intel.smartMoney.optionsVolume.value.sentiment.toUpperCase()})` : 'Data unavailable'}\n`;
    md += `* **SEC 13F Ownership:** ${intel.smartMoney.institutionalOwnershipPercent !== null ? `${intel.smartMoney.institutionalOwnershipPercent}% ownership (${intel.smartMoney.netInstitutionalFlow.toUpperCase()})` : 'Data unavailable'}\n\n`;

    md += `---\n*Report generated by BusinessOS Unified Intelligence platform. Metadata and quotes synced at generation timestamp.*`;

    this.downloadTextFile(md, `${intel.ticker.toLowerCase()}_intelligence_report.md`);
  }

  /**
   * Renders a styled Financial Times print window for a Company Intelligence Report
   */
  public static exportIntelligenceReportToPDF(
    intel: CompanyIntelligence,
    conviction: UserConviction | null
  ) {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Pop-up blocker prevented generating PDF. Please enable pop-ups for this site.');
      return;
    }

    const dateStr = new Date(intel.research.updatedAt).toLocaleString();

    const convictionHtml = conviction
      ? `
        <div style="background-color:#FAF8F5; border:1.5px solid #222; padding:16px 20px; margin-bottom:24px;">
          <h3 style="font-family:'Courier New', monospace; font-size:13px; color:#c2410c; margin:0 0 10px 0; text-transform:uppercase; letter-spacing:1px; font-weight:bold;">
            ✦ Personalized Portfolio Conviction Summary (${conviction.overallScore}/100)
          </h3>
          <div style="display:flex; flex-direction:column; gap:10px; font-size:12px;">
            <div style="border-bottom:1px dashed #D2CAC3; padding-bottom:6px;">
              <strong>Allocation Factor (${conviction.breakdown.allocationFactor.contribution}/25):</strong> ${conviction.breakdown.allocationFactor.explanation}
            </div>
            <div style="border-bottom:1px dashed #D2CAC3; padding-bottom:6px;">
              <strong>Fundamental Quality (${conviction.breakdown.fundamentalFactor.contribution}/25):</strong> ${conviction.breakdown.fundamentalFactor.explanation}
            </div>
            <div style="border-bottom:1px dashed #D2CAC3; padding-bottom:6px;">
              <strong>Buy-The-Dip Premium (${conviction.breakdown.dipFactor.contribution}/25):</strong> ${conviction.breakdown.dipFactor.explanation}
            </div>
            <div>
              <strong>Smart Money Flow (${conviction.breakdown.institutionalFactor.contribution}/25):</strong> ${conviction.breakdown.institutionalFactor.explanation}
            </div>
          </div>
        </div>
      `
      : '';

    printWindow.document.write(`
      <html>
        <head>
          <title>Intelligence Report: ${intel.name}</title>
          <style>
            @media print {
              body { background-color: #FFFFFF !important; }
              .no-print { display: none; }
            }
            body {
              background-color: #FCFAF6;
              color: #111111;
              font-family: 'Georgia', serif;
              padding: 40px;
              max-width: 800px;
              margin: 0 auto;
              border: 1px solid #E5DFD5;
              box-sizing: border-box;
            }
            h1, h2, h3, h4, h5 {
              font-family: 'Times New Roman', Georgia, serif;
              font-weight: normal;
              margin: 0;
            }
            .header {
              text-align: center;
              border-bottom: 2px double #111;
              padding-bottom: 12px;
              margin-bottom: 24px;
            }
            .title {
              font-size: 32px;
              font-weight: bold;
              letter-spacing: -0.5px;
              line-height: 1.15;
              margin: 6px 0;
            }
            .meta {
              font-family: 'Courier New', Courier, monospace;
              font-size: 11px;
              color: #555;
              display: flex;
              justify-content: center;
              gap: 16px;
              text-transform: uppercase;
            }
            .grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 32px;
            }
            .section-title {
              font-size: 14px;
              font-family: 'Courier New', monospace;
              font-weight: bold;
              text-transform: uppercase;
              border-bottom: 1.5px solid #111;
              padding-bottom: 4px;
              margin-bottom: 12px;
            }
            .metric-row {
              display: flex;
              justify-content: space-between;
              font-size: 13px;
              margin-bottom: 6px;
              border-bottom: 1px dashed #E5DFD5;
              padding-bottom: 4px;
            }
          </style>
        </head>
        <body>
          <div class="no-print" style="margin-bottom: 20px; display: flex; justify-content: flex-end; gap: 8px;">
            <button onclick="window.print()" style="font-family:sans-serif; cursor:pointer; background:#222; color:#fff; border:none; padding:8px 16px; font-weight:bold; font-size:12px;">
              Print / Save as PDF
            </button>
            <button onclick="window.close()" style="font-family:sans-serif; cursor:pointer; background:#eee; color:#333; border:1px solid #ccc; padding:8px 16px; font-size:12px;">
              Close
            </button>
          </div>

          <div class="header">
            <span style="font-family:'Courier New', monospace; font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#555;">
              Investment Intelligence Record • Canonical Registry
            </span>
            <div class="title">${intel.name} (${intel.ticker}:${intel.exchange})</div>
            <div class="meta">
              <span>Sector: ${intel.sector}</span>
              <span>•</span>
              <span>Quality Score: ${intel.qualityScore}/100</span>
              <span>•</span>
              <span>As of: ${dateStr}</span>
            </div>
          </div>

          ${convictionHtml}

          <div class="grid">
            <div>
              <div style="margin-bottom: 24px;">
                <div class="section-title">Quality Score Framework</div>
                <div class="metric-row">
                  <span>Economic Moat Rating:</span>
                  <span style="font-family:monospace; font-weight:bold;">${intel.research.moatRating.toUpperCase()} (${intel.qualityBreakdown?.moat.score || 0}/40)</span>
                </div>
                <p style="font-size:12px; font-style:italic; color:#444; line-height:1.4; margin: 4px 0 12px 0;">
                  "${intel.research.moatRationale}"
                </p>
                <div class="metric-row">
                  <span>Leverage Ratio:</span>
                  <span style="font-family:monospace; font-weight:bold;">${intel.research.leverageRatio.toFixed(2)} (${intel.qualityBreakdown?.leverage.score || 0}/30)</span>
                </div>
                <div class="metric-row">
                  <span>Free Cash Flow Margin:</span>
                  <span style="font-family:monospace; font-weight:bold;">${intel.research.freeCashFlowMargin.toFixed(1)}% (${intel.qualityBreakdown?.fcfMargin.score || 0}/30)</span>
                </div>
              </div>

              <div>
                <div class="section-title">Technical Dip Diagnostics</div>
                <div class="metric-row">
                  <span>Dip Active:</span>
                  <span style="font-family:monospace; font-weight:bold; color: ${intel.dip.dipDetected ? '#b45309' : '#006622'}">${intel.dip.dipDetected ? 'YES' : 'NO'}</span>
                </div>
                ${intel.dip.dipDetected ? `
                  <div class="metric-row">
                    <span>Classification:</span>
                    <span style="font-family:monospace; font-weight:bold; text-transform:uppercase;">${intel.dip.classification || 'UNSTABLE'}</span>
                  </div>
                  <div class="metric-row">
                    <span>Z-Score Deviation:</span>
                    <span style="font-family:monospace; font-weight:bold;">${intel.dip.zScore?.toFixed(2)} σ</span>
                  </div>
                  <p style="font-size:12px; font-style:italic; color:#444; line-height:1.4; margin: 4px 0 0 0;">
                    "${intel.dip.catalyst}"
                  </p>
                ` : `
                  <p style="font-size:12px; color:#555; font-style:italic;">No unusual price declines detected. Asset trades within normal volatility bands.</p>
                `}
              </div>
            </div>

            <div>
              <div style="margin-bottom: 24px;">
                <div class="section-title">Institutional & Insider Flow Registry</div>
                
                <div class="metric-row" style="flex-direction:column; align-items:flex-start; gap:4px;">
                  <span style="font-size:12px; font-weight:bold;">Insider Transactions (90d):</span>
                  <span style="font-size:12px; color:#333;">
                    ${intel.smartMoney.insiderTransactions?.value 
                      ? `${intel.smartMoney.insiderTransactions.value.netSharesBought.toLocaleString()} net shares bought (${intel.smartMoney.insiderTransactions.value.totalTransactionsCount} filings)` 
                      : 'Data unavailable'}
                  </span>
                </div>

                <div class="metric-row" style="flex-direction:column; align-items:flex-start; gap:4px;">
                  <span style="font-size:12px; font-weight:bold;">Officer Sentiment:</span>
                  <span style="font-size:12px; color:#333;">
                    ${intel.smartMoney.insiderSentiment?.value 
                      ? `Monthly Purchase Ratio (MSPR): ${intel.smartMoney.insiderSentiment.value.mspr.toFixed(2)}` 
                      : 'Data unavailable'}
                  </span>
                </div>

                <div class="metric-row" style="flex-direction:column; align-items:flex-start; gap:4px;">
                  <span style="font-size:12px; font-weight:bold;">Options Flow Sentiment:</span>
                  <span style="font-size:12px; color:#333;">
                    ${intel.smartMoney.optionsVolume?.value 
                      ? `Put/Call Ratio: ${intel.smartMoney.optionsVolume.value.putCallRatio.toFixed(2)} (${intel.smartMoney.optionsVolume.value.sentiment.toUpperCase()})` 
                      : 'Data unavailable'}
                  </span>
                </div>

                <div class="metric-row" style="flex-direction:column; align-items:flex-start; gap:4px;">
                  <span style="font-size:12px; font-weight:bold;">Institutional SEC Form 13F:</span>
                  <span style="font-size:12px; color:#333;">
                    ${intel.smartMoney.institutionalOwnershipPercent !== null 
                      ? `${intel.smartMoney.institutionalOwnershipPercent}% ownership | Flow: ${intel.smartMoney.netInstitutionalFlow.toUpperCase()}` 
                      : 'Data unavailable'}
                  </span>
                </div>
              </div>
            </div>
          </div>

          <div style="margin-top: 36px; border-top: 1px solid #111; padding-top: 8px; font-family:'Courier New', monospace; font-size:9px; text-align:center; color:#555; text-transform:uppercase;">
            Intelligence dispatch generated dynamically. Financial Times styling template applied.
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
  }
}
