import React, { useState } from 'react';
import { HelpCircle, ShieldAlert, CheckCircle2, Cpu, Clock, RefreshCw, Database } from 'lucide-react';

export interface MetricDoc {
  fullName: string;
  meaning: string;
  whyItMatters: string;
  howCalculated: string;
  dataSource: string;
  refreshFrequency: string;
}

export const METRIC_DEFINITIONS: Record<string, MetricDoc> = {
  RPM: {
    fullName: "Requests Per Minute (RPM)",
    meaning: "The average frequency of API requests sent to AI models within a rolling 60-second window.",
    whyItMatters: "Exceeding provider RPM limits causes HTTP 429 rate-limit errors, triggering failovers or degrading user experience.",
    howCalculated: "Total requests in current window divided by elapsed minutes (or rolling 60s counter).",
    dataSource: "BusinessOS Telemetry Aggregator (Estimated baseline; provider API does not return real-time RPM usage headers).",
    refreshFrequency: "Real-time on every request / 5-second polling"
  },
  TPM: {
    fullName: "Tokens Per Minute (TPM)",
    meaning: "The volume of input prompt and output completion tokens processed per minute.",
    whyItMatters: "High-throughput tasks (e.g. large report generation or data ingestion) can rapidly exhaust TPM limits even with low request counts.",
    howCalculated: "Sum of (promptTokens + completionTokens) across all successful requests in the last 60 seconds.",
    dataSource: "BusinessOS Telemetry Aggregator (Estimated baseline from token counts).",
    refreshFrequency: "Real-time on every request / 5-second polling"
  },
  RPD: {
    fullName: "Requests Per Day (RPD)",
    meaning: "Total volume of API invocations executed since UTC midnight.",
    whyItMatters: "Daily tier limits govern overall organizational capacity and prevent runaway automated scripts from causing unexpected billing spikes.",
    howCalculated: "Cumulative count of all AI execution attempts (including retries and fallbacks) within the current UTC day.",
    dataSource: "BusinessOS Telemetry Aggregator (Estimated baseline; not authoritative provider billing data).",
    refreshFrequency: "Real-time / Updated on each execution"
  },
  PromptTokens: {
    fullName: "Prompt Tokens (Input)",
    meaning: "The number of tokenized text, image, audio, or video units submitted as instructions or context to the AI model.",
    whyItMatters: "Input tokens consume context window budget and directly drive the input cost component of API billing.",
    howCalculated: "Reported directly by model response usage metadata (or estimated via character count / 4 when provider metadata is missing).",
    dataSource: "Live (Provider Reported via usage_metadata.prompt_token_count) or Estimated fallback.",
    refreshFrequency: "Per request execution"
  },
  CompletionTokens: {
    fullName: "Completion Tokens (Output)",
    meaning: "The number of tokenized text or structured units generated by the AI model in response to a prompt.",
    whyItMatters: "Output tokens are typically 3x to 4x more expensive per token than input tokens and determine generation latency.",
    howCalculated: "Reported directly by model response usage metadata.",
    dataSource: "Live (Provider Reported via usage_metadata.candidates_token_count).",
    refreshFrequency: "Per request execution"
  },
  CacheHitRate: {
    fullName: "Cache Hit Rate (%)",
    meaning: "The percentage of AI requests served instantly from the BusinessOS semantic response cache without hitting upstream AI providers.",
    whyItMatters: "High cache hit rates dramatically reduce API costs, eliminate network latency, and protect upstream rate limits.",
    howCalculated: "(Total Cached Responses / Total Requests Today) * 100.",
    dataSource: "Live (BusinessOS Internal Semantic Cache Engine).",
    refreshFrequency: "Updated instantaneously on every request"
  },
  CacheMissRate: {
    fullName: "Cache Miss Rate (%)",
    meaning: "The percentage of requests requiring live execution against an LLM provider due to novel prompts or expired cache TTLs.",
    whyItMatters: "Indicates how much of user query volume requires active computational inference and incurring API charges.",
    howCalculated: "100 - Cache Hit Rate (or (Live API Calls / Total Requests) * 100).",
    dataSource: "Live (BusinessOS Internal Semantic Cache Engine).",
    refreshFrequency: "Updated instantaneously on every request"
  },
  AverageLatency: {
    fullName: "Average Latency (ms)",
    meaning: "The mean end-to-end duration from initial request dispatch to full response receipt from the AI provider.",
    whyItMatters: "Directly affects UI responsiveness and perceived platform speed. Spikes indicate upstream network congestion or model throttling.",
    howCalculated: "Sum of all request execution durations (ms) divided by total completed requests in the time window.",
    dataSource: "Live (BusinessOS Orchestrator Execution Timer).",
    refreshFrequency: "Rolling average updated on each completed request"
  },
  RetryCount: {
    fullName: "API Retry Count",
    meaning: "The number of automated retry attempts executed by the orchestrator following transient network errors or HTTP 5xx responses.",
    whyItMatters: "High retry counts indicate instability in the upstream provider node or intermittent network degradation.",
    howCalculated: "Cumulative count of exponential backoff retry loops triggered before declaring failure or cascading to fallback.",
    dataSource: "Live (BusinessOS Orchestrator Error Handler).",
    refreshFrequency: "Real-time per request"
  },
  Cooldown: {
    fullName: "Model Cooldown Timer",
    meaning: "The duration a model is temporarily quarantined from primary routing after encountering consecutive rate-limits (HTTP 429) or hard failures.",
    whyItMatters: "Prevents continuous hammering of an unresponsive endpoint, ensuring immediate failover to healthy secondary models.",
    howCalculated: "Exponential backoff timer (default 30s to 300s) initiated upon threshold failure violation.",
    dataSource: "Live (BusinessOS Circuit Breaker State).",
    refreshFrequency: "1-second countdown tick"
  },
  Fallback: {
    fullName: "Fallback Activation Events",
    meaning: "The count of requests that failed on their primary target model and were successfully salvaged by cascading down the priority chain.",
    whyItMatters: "Measures the resilience of the AI infrastructure. High fallback rates indicate primary model SLA degradation.",
    howCalculated: "Count of telemetry records where selectedModel !== fallbackModel and success === true.",
    dataSource: "Live (BusinessOS Failover Telemetry).",
    refreshFrequency: "Real-time per execution"
  },
  ProviderHealth: {
    fullName: "Provider Node Health Status",
    meaning: "The aggregated operational condition of an upstream AI vendor (e.g. Google Gemini, OpenAI, Anthropic).",
    whyItMatters: "Determines whether the orchestrator should route traffic to a provider or divert entirely to multi-cloud alternatives.",
    howCalculated: "Synthesized from rolling success rates, average latency against SLAs, and active circuit breaker states.",
    dataSource: "Live (BusinessOS Health Monitor & Active Synthetic Probing).",
    refreshFrequency: "Every 15 seconds or upon circuit breaker trip"
  },
  ModelHealth: {
    fullName: "Model Operational Status",
    meaning: "The specific operational readiness of an individual model checkpoint (e.g. gemini-3.1-pro-preview).",
    whyItMatters: "Allows fine-grained routing around degraded models while keeping other models from the same vendor active.",
    howCalculated: "Evaluated via recent error classification ratios and cooldown timer state.",
    dataSource: "Live (BusinessOS Registry Status Tracker).",
    refreshFrequency: "Real-time per execution"
  },
  EstimatedCost: {
    fullName: "Estimated Financial Cost ($)",
    meaning: "The projected financial expenditure calculated in real-time based on published model token pricing.",
    whyItMatters: "Provides immediate financial visibility before monthly vendor invoices arrive, enabling proactive budget management.",
    howCalculated: "(Prompt Tokens * Input Price / 1M) + (Completion Tokens * Output Price / 1M).",
    dataSource: "Estimated (BusinessOS Cost Calculation Engine applied to token telemetry).",
    refreshFrequency: "Real-time per request / Summarized daily"
  },
  ActualCost: {
    fullName: "Actual Reconciled Cost ($)",
    meaning: "The exact billed expenditure finalized by provider invoices or billing export feeds.",
    whyItMatters: "Authoritative financial record for accounting, departmental chargebacks, and margin analysis.",
    howCalculated: "Reconciled against provider billing exports (e.g. GCP Cloud Billing / OpenAI Organization usage API).",
    dataSource: "Live (Provider Reported via billing API synchronization).",
    refreshFrequency: "Daily batch reconciliation"
  },
  SuccessRate: {
    fullName: "Execution Success Rate (%)",
    meaning: "The percentage of AI requests that completed successfully (either on primary or fallback) without returning an unhandled error to the user.",
    whyItMatters: "The primary Key Performance Indicator (KPI) for platform reliability and user satisfaction.",
    howCalculated: "(Total Successful Requests / Total Request Attempts) * 100.",
    dataSource: "Live (BusinessOS Telemetry Logs).",
    refreshFrequency: "Real-time rolling calculation"
  }
};

interface MetricTooltipProps {
  metricKey: keyof typeof METRIC_DEFINITIONS | string;
  children?: React.ReactNode;
  label?: string;
}

export const MetricTooltip: React.FC<MetricTooltipProps> = ({ metricKey, children, label }) => {
  const [show, setShow] = useState(false);
  const doc = METRIC_DEFINITIONS[metricKey] || {
    fullName: label || metricKey,
    meaning: "Operational metric tracked by the BusinessOS AI Orchestration Engine.",
    whyItMatters: "Provides visibility into system performance, reliability, or cost.",
    howCalculated: "Aggregated from real-time execution logs and telemetry events.",
    dataSource: "BusinessOS Telemetry Engine",
    refreshFrequency: "Real-time"
  };

  return (
    <span 
      style={{ position: 'relative', display: 'inline-flex', alignItems: 'center', gap: '0.3rem', cursor: 'help' }}
      onMouseEnter={() => setShow(true)}
      onMouseLeave={() => setShow(false)}
    >
      {children || <span>{doc.fullName}</span>}
      <HelpCircle size={13} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />

      {show && (
        <div style={{
          position: 'absolute',
          bottom: '100%',
          left: '50%',
          transform: 'translateX(-50%)',
          marginBottom: '8px',
          width: '320px',
          background: '#1e1b18',
          color: '#fcfaf6',
          border: '1px solid #c4b9a7',
          borderRadius: '6px',
          padding: '0.85rem',
          boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
          zIndex: 99999,
          fontSize: '0.75rem',
          fontFamily: 'var(--font-sans)',
          lineHeight: '1.4',
          textAlign: 'left',
          pointerEvents: 'none'
        }}>
          <div style={{ fontWeight: 'bold', fontSize: '0.85rem', color: '#f59e0b', borderBottom: '1px solid #3d362e', paddingBottom: '0.4rem', marginBottom: '0.5rem' }}>
            {doc.fullName}
          </div>
          
          <div style={{ marginBottom: '0.5rem' }}>
            <span style={{ color: '#a855f7', fontWeight: 600, fontSize: '0.65rem', textTransform: 'uppercase', display: 'block' }}>Meaning</span>
            {doc.meaning}
          </div>

          <div style={{ marginBottom: '0.5rem' }}>
            <span style={{ color: '#10b981', fontWeight: 600, fontSize: '0.65rem', textTransform: 'uppercase', display: 'block' }}>Why It Matters</span>
            {doc.whyItMatters}
          </div>

          <div style={{ marginBottom: '0.5rem' }}>
            <span style={{ color: '#06b6d4', fontWeight: 600, fontSize: '0.65rem', textTransform: 'uppercase', display: 'block' }}>How Calculated</span>
            <code style={{ background: '#2d2822', padding: '2px 4px', borderRadius: '3px', fontSize: '0.7rem', color: '#e2dacd', display: 'block', marginTop: '2px' }}>
              {doc.howCalculated}
            </code>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', borderTop: '1px solid #3d362e', paddingTop: '0.5rem', fontSize: '0.65rem', color: '#c4b9a7' }}>
            <div>
              <strong style={{ color: '#fff', display: 'block' }}>Data Source:</strong>
              {doc.dataSource}
            </div>
            <div>
              <strong style={{ color: '#fff', display: 'block' }}>Refresh:</strong>
              {doc.refreshFrequency}
            </div>
          </div>

          {/* Tooltip arrow */}
          <div style={{
            position: 'absolute',
            top: '100%',
            left: '50%',
            transform: 'translateX(-50%)',
            borderWidth: '6px',
            borderStyle: 'solid',
            borderColor: '#1e1b18 transparent transparent transparent'
          }} />
        </div>
      )}
    </span>
  );
};

interface SourceBadgeProps {
  source: 'live' | 'estimated' | 'cached';
  lastUpdated?: string | number | Date;
  details?: string;
}

export const SourceBadge: React.FC<SourceBadgeProps> = ({ source, lastUpdated, details }) => {
  const timestampStr = lastUpdated 
    ? new Date(lastUpdated).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
    : new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });

  let bg = '#e0f2fe';
  let border = '#bae6fd';
  let color = '#0369a1';
  let label = 'Live (Provider Reported)';
  let icon = <CheckCircle2 size={11} />;

  if (source === 'estimated') {
    bg = '#fef3c7';
    border = '#fde68a';
    color = '#b45309';
    label = 'Estimated (BusinessOS)';
    icon = <Clock size={11} />;
  } else if (source === 'cached') {
    bg = '#f3e8ff';
    border = '#e9d5ff';
    color = '#6b21a8';
    label = 'Cached Response';
    icon = <Database size={11} />;
  }

  return (
    <span
      title={`${label} — Last Updated at ${timestampStr}. ${details || (source === 'estimated' ? 'Derived from telemetry logs; not authoritative provider billing data.' : 'Directly reported by vendor API.')}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        background: bg,
        border: `1px solid ${border}`,
        color: color,
        fontSize: '0.6rem',
        fontWeight: 'bold',
        padding: '1px 5px',
        borderRadius: '3px',
        fontFamily: 'var(--font-mono)',
        cursor: 'help',
        verticalAlign: 'middle',
        whiteSpace: 'nowrap'
      }}
    >
      {icon}
      <span>{label}</span>
      <span style={{ opacity: 0.7, fontSize: '0.55rem', marginLeft: '2px' }}>({timestampStr})</span>
    </span>
  );
};
